### ISSUE TITLE
Ask for Supplementary and Helen Dataset

### ISSUE THREAD

**Issue by shaonianruntu** [carolineec/informative-drawings#12]
Dear author,

I find that you have greatly improved the quality of face pen painting synthesis after using Helen dataset instead of Apdrawing dataset. I'm very interested in it. Can you provide the supplemental of the paper and the experimental dataset, as well as the training / test segmentation strategy of the dataset ?

Thanks 
Nan

**Comment by krummrey** [comment]
The Helen Dataset is here:
[http://www.ifp.illinois.edu/~vuongle2/helen/](http://www.ifp.illinois.edu/~vuongle2/helen/)

**Comment by shaonianruntu** [comment]
> The Helen Dataset is here: http://www.ifp.illinois.edu/~vuongle2/helen/
> 
> The supplementaries are in the PDF. Chapter 6.

Thank You.
