### ISSUE TITLE
None Cuda dependent version 

### ISSUE THREAD

**Issue by krummrey** [carolineec/informative-drawings#4]
Hi, 
I have a Mac with a M1 CPU and no access to a Cuda device. Is it possible to run the model without it?
I've tried removing all .cuda() calls in test.py and loading with:`map_location=torch.device('cpu')`

Running test.py through this error:

`python test.py --name anime_style --dataroot examples/test                             
Namespace(name='anime_style', checkpoints_dir='checkpoints', results_dir='results', geom_name='feats2Geom', batchSize=1, dataroot='examples/test', depthroot='', input_nc=3, output_nc=1, geom_nc=3, every_feat=1, num_classes=55, midas=0, ngf=64, n_blocks=3, size=256, cuda=True, n_cpu=8, which_epoch='latest', aspect_ratio=1.0, mode='test', load_size=256, crop_size=256, max_dataset_size=inf, preprocess='resize_and_crop', no_flip=False, norm='instance', predict_depth=0, save_input=0, reconstruct=0, how_many=100)
loaded checkpoints/anime_style/netG_A_latest.pth
Traceback (most recent call last):
  File "/Users/jan/Documents/ML/informative-drawings/test.py", line 108, in <module>
    dataloader = DataLoader(test_data, batch_size=opt.batchSize, shuffle=False)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/drawings/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 200, in __init__
    if isinstance(dataset, IterableDataset):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/drawings/lib/python3.10/typing.py", line 1469, in __instancecheck__
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols`

I'm not a deveopler, any idea how I might get it to run?

**Comment by josephrocca** [comment]
I can't help you with your specific error, but I just want to note that it definitely doesn't require CUDA - it even runs with Web Assembly (which is CPU-based) in the browser, which might be the easiest way for you to use it as a non-developer:

* https://josephrocca.github.io/image-to-line-art-js/
* https://github.com/josephrocca/image-to-line-art-js

**Comment by krummrey** [comment]
Thanks for the Web version you have provided.
I have also tried the [Pull](https://github.com/carolineec/informative-drawings/pull/7) which works great for me.
